# Generated by Django 5.1.3 on 2024-11-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_checkout_is_approved_alter_checkout_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='checkout',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
